build: Trigger Docker build on (nightly) release (#448)
- remove release-publish.yml workflow again
- add logic of the workflow to nightly-build.yml and release.yml
- align nightly-build.yml and release.yml more to each other

related to operaton/operaton-docker#2

diff --git a/.github/workflows/nighly-build.yml b/.github/workflows/nighly-build.yml
--- a/.github/workflows/nighly-build.yml
+++ b/.github/workflows/nighly-build.yml
@@ -83,13 +83,6 @@ jobs:
             **/target/surefire-reports/*.xml
             target/project-reports.zip
           key: ${{ github.run_id }}-build-artifacts
-      - name: Publish Test Report
-        if: ${{ github.event.inputs.skip_tests == 'false' || github.event_name == 'schedule' }}
-        # https://github.com/marketplace/actions/junit-report-action
-        uses: mikepenz/action-junit-report@v4
-        with:
-          report_paths: ${{ github.workspace }}/**/target/surefire-reports/*.xml
-          require_passed_tests: true
 
   release:
     name: Release
@@ -129,3 +122,46 @@ jobs:
           JRELEASER_MAVENCENTRAL_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
           JRELEASER_DRY_RUN: ${{ github.event_name == 'schedule' && false || github.event.inputs.dry_run }}
           JRELEASER_PRERELEASE_ENABLED: true
+
+      - name: Publish Test Report
+        if: ${{ github.event_name == 'schedule' || github.event.inputs.skip_tests == 'false'}}
+        # https://github.com/marketplace/actions/junit-report-action
+        uses: mikepenz/action-junit-report@v4
+        with:
+          report_paths: ${{ github.workspace }}/**/target/surefire-reports/*.xml
+          require_passed_tests: true
+
+      - name: Archive Reports
+        uses: actions/upload-artifact@v4
+        with:
+          name: reports
+          path: |
+            **/target/reports/**
+
+      - name: Archive Staging Repo
+        uses: actions/upload-artifact@v4
+        with:
+          name: staging
+          path: |
+            ./*/staging-deploy/**
+          retention-days: 10
+
+  post_release:
+    name: Post-Release
+    runs-on: ubuntu-24.04
+    needs:
+      - build
+      - release
+    steps:
+      - name: Notify Docker Repository
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+            -H "Authorization: Bearer ${{ secrets.DOCKER_ACTION_DISPATCH_TOKEN }}" \
+            -H "Accept: application/vnd.github.v3+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            -d '{"ref":"main","inputs":{"version": "${{ needs.build.outputs.version}}","snapshot": "true"}}' \
+            https://api.github.com/repos/operaton/operaton-docker/actions/workflows/build-test-and-publish.yml/dispatches)
+          if [ "$response" -ne 204 ]; then
+            echo "Failed to notify Docker repository. HTTP response code: $response"
+            exit 1
+          fi
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -88,6 +88,7 @@ jobs:
         with:
           path: |
             distro/**/*.tar.gz
+            distro/**/*.zip
             distro/webjar/target/operaton-webapp-webjar-*.jar
             ./*/staging-deploy/**
             **/target/reports/**
@@ -113,6 +114,7 @@ jobs:
         with:
           path: |
             distro/**/*.tar.gz
+            distro/**/*.zip
             distro/webjar/target/operaton-webapp-webjar-*.jar
             ./*/staging-deploy/**
             **/target/reports/**
@@ -159,7 +161,9 @@ jobs:
 
   post_release:
     name: Post-Release
-    needs: release
+    needs:
+      - precheck
+      - release
     runs-on: ubuntu-24.04
     steps:
       - name: Check out the code
@@ -183,4 +187,17 @@ jobs:
             git config --local user.email "github-actions[bot]@users.noreply.github.com"
             git commit --allow-empty -am "[releng] Bump version to $NEXT_VERSION"
             git push origin ${{github.event.inputs.release_branch}}
+          fi
+
+      - name: Notify Docker Repository
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+            -H "Authorization: Bearer ${{ secrets.DOCKER_ACTION_DISPATCH_TOKEN }}" \
+            -H "Accept: application/vnd.github.v3+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            -d '{"ref":"main","inputs":{"version": "${{ needs.precheck.outputs.version}}","snapshot": "false"}}' \
+            https://api.github.com/repos/operaton/operaton-docker/actions/workflows/build-test-and-publish.yml/dispatches)
+          if [ "$response" -ne 204 ]; then
+            echo "Failed to notify Docker repository. HTTP response code: $response"
+            exit 1
           fi
