build: Fix release-publish.yml (#445)
Fix the syntax issues on the workflow and evaluate response

diff --git a/.github/workflows/release-publish.yml b/.github/workflows/release-publish.yml
--- a/.github/workflows/release-publish.yml
+++ b/.github/workflows/release-publish.yml
@@ -16,10 +16,11 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  outputs:
-    version: ${{ github.event.release.tag_name || steps.version.outputs.version }}
-    snapshot: ${{ github.event.release.tag_name == 'early_access' || github.event.inputs.tag_name == 'early_access' }}
   prepare:
+    runs-on: ubuntu-24.04
+    outputs:
+      version: ${{ github.event.release.tag_name || steps.version.outputs.version }}
+      snapshot: ${{ github.event.release.tag_name == 'early_access' || github.event.inputs.tag_name == 'early_access' }}
     steps:
       - name: Checkout Code
         if: github.event_name == 'workflow_dispatch'
@@ -38,11 +39,16 @@ jobs:
     runs-on: ubuntu-24.04
     needs:
       - prepare
-    run: |
-      curl -X POST \
-        -H "Authorization: Bearer ${{ secrets.DOCKER_ACTION_DISPATCH_TOKEN }}" \
-        -H "Accept: application/vnd.github.v3+json" \
-        -H "X-GitHub-Api-Version: 2022-11-28" \
-        -d '{"event_type": "release_published", "client_payload": {"version": "${{ needs.prepare.outputs.version }}","snapshot":"${{ needs.prepare.outputs.snapshot }}"}}' \
-        https://api.github.com/repos/operaton/operaton-docker/dispatches
-      
+    steps:
+      - name: Notify Docker Repository
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+            -H "Authorization: Bearer ${{ secrets.DOCKER_ACTION_DISPATCH_TOKEN }}" \
+            -H "Accept: application/vnd.github.v3+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            -d '{"event_type": "release_published", "client_payload": {"version": "${{ needs.prepare.outputs.version }}","snapshot":"${{ needs.prepare.outputs.snapshot }}"}}' \
+            https://api.github.com/repos/operaton/operaton-docker/dispatches)
+          if [ "$response" -ne 200 ]; then
+            echo "Failed to notify Docker repository. HTTP response code: $response"
+            exit 1
+          fi
