build: Evaluate response

diff --git a/.github/workflows/release-publish.yml b/.github/workflows/release-publish.yml
--- a/.github/workflows/release-publish.yml
+++ b/.github/workflows/release-publish.yml
@@ -42,9 +42,13 @@ jobs:
     steps:
       - name: Notify Docker Repository
         run: |
-          curl -X POST \
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
             -H "Authorization: Bearer ${{ secrets.DOCKER_ACTION_DISPATCH_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             -d '{"event_type": "release_published", "client_payload": {"version": "${{ needs.prepare.outputs.version }}","snapshot":"${{ needs.prepare.outputs.snapshot }}"}}' \
-            https://api.github.com/repos/operaton/operaton-docker/dispatches
+            https://api.github.com/repos/operaton/operaton-docker/dispatches)
+          if [ "$response" -ne 200 ]; then
+            echo "Failed to notify Docker repository. HTTP response code: $response"
+            exit 1
+          fi
